apps/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from apps.sitemaps import BlogSitemap, VacancySitemap
from tour.views import travel
from home.views import index
from premise.views import premise, platia


from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

#from educa.views import CourseListView
from django.contrib.staticfiles import views

sitemaps = {
  'blogs': BlogSitemap,
  'vacancy': VacancySitemap
}

urlpatterns = [
    url(r'^$', platia, name='index'),
    url(r'^premise/', include('premise.urls')),
    url(r'^home/', include('home.urls')),
    url(r'^college/', include('college.urls')),
    #url(r'^$', CourseListView.as_view(), name='course_list'),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/logout/$', auth_views.logout, name='logout'),
    url(r'^accounts/user/login/$', auth_views.login, {'template_name': 'user_login.html'}, name='user_login'),
    url(r'^accounts/user/logout/$', auth_views.logout, {'template_name': 'user_logged_out.html'}, name='user_logout'),
    url(r'^admin/', admin.site.urls),
    #url(r'^educa/', include('educa.urls')),
    url(r'^events/', include('events.urls')),
    url(r'^tour/', include('tour.urls')),
    url(r'^student/', include('student.urls')),
    url(r'^users/', include('finders.urls')),
    url('^', include('django.contrib.auth.urls')),
    url(r'^chaining/', include('smart_selects.urls')),




    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),







]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/urls.py
from django.conf.urls import url
from . import views

app_name = 'events'
urlpatterns = [
           url(r'^apply/$', views.apply_course, name='apply'),
           url(r'^blog/$', views.blog_list, name='blog'),
           url(r'^blog/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/' \
           r'(?P<blog>[-\w]+)/$',
           views.blog_detail,
           name='blog-detail'),

           url(r'^allevents/$', views.allevents, name='allevents'),

]

home/urls.py
from . import views
from django.conf.urls import url
from .views import index


app_name = 'home'
urlpatterns = [
         url(r'^$', index, name='index'),
         url(r'^allnews/', views.allnews, name='allnews'),
         url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.allnews,
          name='allnews_by_tag'),
         url(r'^new/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/' \
           r'(?P<new>[-\w]+)/$',
           views.latest_detail,
           name='news'),
         ]

platia/urls.py
from django.conf.urls import url
from . import views
from .views import travel


app_name = 'tour'
urlpatterns = [



    url(r'^travel/', travel, name='travel'),
    url(r'^alltrips/', views.alltrips, name='alltrips'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.alltrips,
          name='alltrips_by_tag'),
    url(r'^trip/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/' \
           r'(?P<trip>[-\w]+)/$',
           views.trip_detail,
           name='trip-detail'),

]

home/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from taggit.managers import TaggableManager

from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ('-date_added',)
        verbose_name_plural = 'Categories'

    def __unicode__(self):
            return unicode(self.title)


class Writer(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    date_added = models.DateField(auto_now_add=True)
    picture = ProcessedImageField(upload_to='writers', processors=[ResizeToFill(100, 100)],
                                          format='JPEG',
                                          options={'quality': 100}, blank=True)

    def __unicode__(self):
        return unicode(self.name)


class Latest(models.Model):
    STATUS = (
        ('published', 'PUBLISHED'),
        ('draft', 'DRAFT'))
    PRIORITY = (
        ('yes', 'YES'),
        ('no', 'NO'))
    title = models.CharField(max_length=200)
    story = models.TextField()
    created = models.DateField(auto_now_add=True)
    summary = models.TextField()
    slug = models.SlugField(unique_for_date='created', default='latest')
    photo = ProcessedImageField(upload_to='latest', processors=[ResizeToFill(1778, 1000)],
                                          format='JPEG',
                                          options={'quality': 100}, blank=True)
    thumbnail = ProcessedImageField(upload_to='latest', processors=[ResizeToFill(100, 100)],
                                          format='JPEG',
                                          options={'quality': 100}, blank=True)
    category = models.ForeignKey(Category)
    writer = models.ForeignKey(Writer)
    status = models.CharField(max_length=50, choices=STATUS, default='draft')
    tags = TaggableManager()
    priority = models.CharField(max_length=50, choices=PRIORITY, default='no')
    video = models.URLField(blank=True)

    class Meta:
        ordering = ('-created',)

    def __unicode__(self):
        return unicode(self.title)

    def get_absolute_url(self):
        return reverse('home:news', args=[self.created.year,
                                          self.created.strftime('%m'),
                                          self.created.strftime('%d'),
                                          self.slug])


class Testimonial(models.Model):
    title = models.CharField(max_length=50, blank=True)
    body = models.TextField()
    photo = ProcessedImageField(upload_to='latest', processors=[ResizeToFill(200, 150)],
                                format='JPEG',
                                options={'quality': 100}, blank=True)
    person = models.CharField(verbose_name='Testimonial From', blank=True, max_length=50)
    course = models.CharField(blank=True, max_length=50)


class Display(models.Model):
    title = models.CharField(max_length=50, blank=True)
    body = models.TextField()
    photo = ProcessedImageField(upload_to='latest', processors=[ResizeToFill(780, 354)],
                                format='JPEG',
                                options={'quality': 100}, blank=True)

home/views.py
from django.shortcuts import render, get_object_or_404
from models import Latest
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from taggit.models import Tag
from django.db.models import Count





def index(request):
    news = Latest.objects.order_by('-created')[:4]
    paginator = Paginator(news, 4)
    page = request.GET.get('page')
    try:
        news = paginator.page(page)
    except PageNotAnInteger:
        news = paginator.page(1)
    except EmptyPage:
        news = paginator.page(paginator.num_pages)
    return render(request, 'home/index.html', {'news': news, 'page': page})


def allnews(request, tag_slug=None):
    news = Latest.objects.order_by('-created')
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        news = news.filter(tags__in=[tag])

    paginator = Paginator(news, 1)
    page = request.GET.get('page')
    try:
        news = paginator.page(page)
    except PageNotAnInteger:
        news = paginator.page(1)
    except EmptyPage:
        news = paginator.page(paginator.num_pages)
    return render(request, 'home/allnews.html', {'news': news, 'page': page, 'tag' : tag})


def latest_detail(request, year, month, day, new):
    new = get_object_or_404(Latest, slug=new)
    new_tag_ids = new.tags.values_list('id', flat=True)
    similar_news = Latest.objects.filter(tags__in=new_tag_ids).exclude(id=new.id)
    similar_news = similar_news.annotate(same_tags=Count('tags')).order_by('-same_tags', '-created')[:3]
    return render(request, 'home/news.html', {'new': new, 'similar_news': similar_news})

home/templates/home/allnews.html
{% extends 'tour/main.html' %}
{% load staticfiles %}
{% block title_block %}
    We Raise Manpower
    {% endblock %}
{% block body_block %}

{% block content %}
<h5 class="center" style=" margin-top: 1.5%; margin-bottom: 0.001%; font-family: 'Oswald',Bold; font-size: 40px">ALL NEWS</h5>
{% if news %}

{% if tag %}
<h2>News tagged with "{{ tag.name }}"</h2>
{% endif %}

 <div class="contain">
<div class="grid-x grid-margin-x">
       {% for new in news %}
        <div class="cell large-3">
        <div class="news-card-tag">

  <p class="tags">
      Tags:
      {% for tag in new.tags.all %}
          <span class="label"><a href="{% url "home:allnews_by_tag" tag.slug %}">{{ tag.name }}</a>
          </span>

{% if not forloop.last %}, {% endif %}
{% endfor %}
</p>
</div>

<div class="card news-card">
{% if new.photo %}
    <img src="{{ new.photo.url }}">
    {% endif %}
  <div class="card-section">

    <article class="news-card-article">
      <h4 class="news-card-title"><a href="{{ new.get_absolute_url }}">{{ new.title }}</a></h4>
      <p class="news-card-description">{{ new.body|truncatewords:10 }}</p>
    </article>

</div>


</div>
    </div>
{% endfor %}

</div>

</div>



{% else %}
<p>No news yet</p>
{% endif %}

          <div class="pagi">
          {% if news.has_other_pages %}
<ul class="pagination-pointed pagination text-center" role="navigation" aria-label="Pagination">
    {% if news.has_previous %}
        <li class="pagination-previous"><a class="pagination-pointed-button" href="?page={{ news.previous_page_number }}" >Previous <span class="show-for-sr">Page</span></a></li>
        {% else %}
  <li class="pagination-previous disabled">Previous <span class="show-for-sr">Page</span></li>
        {% endif %}
    {% for i in  news.paginator.page_range %}
    {% if news.number == i %}
  <li class="current"><span class="show-for-sr">You're on page</span> {{ i }}</li>
        {% else %}
  <li><a class="pagination-pointed-button" href="?page={{ i }}" aria-label="Page 2">{{ i }}</a></li>
  {% endif %}
    {% endfor %}
    {% if news.has_next %}
  <li class="pagination-next"><a class="pagination-pointed-button" href="?page={{ news.next_page_number }}" aria-label="Next page">Next <span class="show-for-sr">page</span></a></li>
        {% endif %}
</ul>
    {% endif %}
          </div>



    {% if tag.name in tag %}
      {% if news.has_other_pages %}
    <ul class="pagination-pointed pagination text-center" role="navigation" aria-label="Pagination">
    {% if news.has_previous %}
        <li class="pagination-previous"><a class="pagination-pointed-button" href="?page={{ news.previous_page_number }}" >Previous <span class="show-for-sr">Page</span></a></li>
        {% else %}
  <li class="pagination-previous disabled">Previous <span class="show-for-sr">Page</span></li>
        {% endif %}
    {% for i in  news.paginator.page_range %}
    {% if news.number == i %}
  <li class="current"><span class="show-for-sr">You're on page</span> {{ i }}</li>
        {% else %}
  <li><a class="pagination-pointed-button" href="?page={{ i }}" aria-label="Page 2">{{ i }}</a></li>
  {% endif %}
    {% endfor %}
    {% if news.has_next %}
  <li class="pagination-next"><a class="pagination-pointed-button" href="?page={{ news.next_page_number }}" aria-label="Next page">Next <span class="show-for-sr">page</span></a></li>
        {% endif %}
</ul>
    {% endif %}
    {% endif %}
{% endblock %}

{% endblock %}

home/templates/home/index.html
{%load i18n staticfiles %}
<!doctype html>
<html class="no-js" lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WHAT EMBU NEEDS</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.0/css/foundation-flex.css">
      <link href="{% static "css/foundation.css" %}" rel="stylesheet">

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <link href="{% static "css/app.css" %}" rel="stylesheet">
    <link href="{% static "fonts/slick.svg" %}" rel="stylesheet">
	<link href="{% static "fonts/slick.eot" %}" rel="stylesheet">
	<link href="{% static "fonts/slick.ttf" %}" rel="stylesheet">
	<link href="{% static "fonts/slick.woff" %}" rel="stylesheet">
	<link href="{% static "css/slick-theme.css" %}" rel="stylesheet">
	<link href="{% static "css/" %}" rel="stylesheet">

  <link href="https://fonts.googleapis.com/css?family=Chela+One|Coda+Caption:800|Fira+Sans|Gaegu|Hind|Knewave|Lato|Libre+Baskerville|Lora|Markazi+Text|Merienda|Merriweather|Montserrat|Noto+Sans|Noto+Serif|Open+Sans|Open+Sans+Condensed:300|Oswald|PT+Sans|PT+Sans+Narrow|Playfair+Display|Poppins|Raleway|Roboto|Roboto+Condensed|Roboto+Slab|Rubik|Slabo+27px|Source+Sans+Pro|Ubuntu" rel="stylesheet">
  </head>
  <body>
  <div data-sticky-container>
  <nav class="fixed top-bar topbar-responsive">
  <div class="top-bar-title">
    <span data-responsive-toggle="topbar-responsive" data-hide-for="medium">
      <button class="menu-icon" type="button" data-toggle></button>
    </span>
    <a class="topbar-responsive-logo" style="font-family:'Ubuntu', Bold; font-size: 30px; color: red" href="#"><strong>Embu</strong></a>
  </div>
  <div id="topbar-responsive" class="topbar-responsive-links">
    <div class="top-bar-right">
      <ul class="menu simple vertical medium-horizontal">
        <li style="font-family:'Ubuntu', serif; font-size: 25px; color: black"><a href="#"> Business </a></li>
        <li style="font-family:'Ubuntu', Bold; font-size: 25px; color: white"><a href="#">Events</a></li>
          <li style="font-family:'Ubuntu', Bold; font-size: 25px; color: white"><a href="#">Videos</a></li>
        <li style="font-family:'Ubuntu', Bold; font-size: 25px; color: black"><a href="{% url 'tour:alltrips' %}">All News</a></li>
      </ul>
    </div>
  </div>
</nav>
      {% for message in messages %}
    {% if 'success' in message.tags %}
<div data-closable class="callout alert-callout-border success">
  <strong><i class="fa fa-check"></i><i class="fa fa-check"></i></strong> - {{ message|safe }}.

  <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
    <span aria-hidden="true">&times;</span>
  </button>
</div>
    {% endif %}
{% endfor %}
{% for message in messages %}
    {% if 'error' in message.tags %}
<div data-closable class="callout alert-callout-border alert radius">
  <strong>OOPS</strong> - {{ message|safe }}.
  <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
    <span aria-hidden="true">&times;</span>
  </button>
</div>
    {% endif %}
{% endfor %}
</div>

   {% load display_tags %}
    {% get_latest_displays %}
<div class="row expanded collapse">
  <div class="column">
      {% for display in latest_displays %}
    <div class="large-article-header">
      <div class="large-article-header-content">
        <div class="center-container">
          <div class="article-date">
            <p>{{ display.created }}</p>
          </div>
          <div class="article-title">
              <a href="{{ display.get_absolute_url }}"><h1 style="  font-family:'Oswald', bold; font-size: 50px; color: darkgoldenrod">{{ display.title }}</h1></a>
          </div>
          <div class="article-details">
            <div class="article-author">

              <a href="#">By {{ display.writer.name }}</a>
            </div>
          </div>
        </div>
      </div>
    </div>
      {% endfor %}
  </div>
</div>



<div class="content">
<div class="wording">
    {% load news_tag %}
    {% get_latest_news %}
<h2 style=" text-align:center; font-family:'Oswald', bold; font-size: 40px; color: black">Breaking News</h2>
</div>
{% for new in latest_news %}
    <div class="wide-article-link">
  <div class="grid-x">
      <a href="{{ new.get_absolute_url }}">
    <div class="cell small-12 medium-9 large-9">
      <h4 class="article-title" style="  font-family:'Ubuntu', bold; font-size: 20px; color: red">
        <a href="#">
          {{ new.title }}
        </a>
      </h4>
 <p class="article-author" ><em>By <a href="#">{{ new.writer.name }}</a></em></p>
      <p class="article-elipsis" style="  font-family:'Roboto Slab', bold; font-size: 20px; color: black">{{ new.summary }} <a href="{{ new.get_absolute_url }}" class="read-more">Read more</a></p>
      <div class="article-social">
        <a href="#" class="button social comments">
          <i class="fa fa-comments-o" aria-hidden="true"></i>
        </a>
        <a href="#" class="button social facebook">
          <i class="fa fa-facebook fa-lg" aria-hidden="true"></i>
        </a>
        <a href="#" class="button social twitter">
          <i class="fa fa-twitter fa-lg" aria-hidden="true"></i>
        </a>
        <a href="#" class="button social linkedin">
          <i class="fa fa-linkedin fa-lg" aria-hidden="true"></i>
        </a>
        <a href="#" class="button social google-plus">
          <i class="fa fa-google-plus fa-lg" aria-hidden="true"></i>
        </a>
      </div>

    </div>
    <div class="cell small-12 medium-3 large-3">
        <div style="margin-top: 60px;">
      <img src="{{ new.thumbnail.url }}">
        </div>
    </div>
      </a>
  </div>
</div>


    {% endfor %}
<div class="article-row-section">
  <div class="article-row-section-inner">
 {% load politics_tag  %}
      {% get_politics_news%}
    <h2 class="article-row-section-header" style="font-family: Lato; color: black">Politics News</h2>
      {% for new in politics_news %}
    <a href="{{ new.get_absolute_url }}">
      <article class="article-row">
        <div class="article-row-img">
            {% if new.thumbnail %}
          <img src="{{ new.thumbnail.url }}" alt="news" />
            {% endif %}
        </div>
        <div class="article-row-content">
          <h5 class="article-row-content-header" style="font-family: Roboto, Bold; font-size: 25px; color: blue">{{ new.title }}</h5>
          <p class="article-row-content-description">{{ new.summary }}</p>
        </div>
      </article>
    </a>
      {% endfor %}
  </div>
</div>
<div style="text-align:center ; font-family:'Lato', serif; font-size: 25px; color: red">
<a href="{% url 'home:allnews' %}" class= "">View All Politics News</a>
</div>

<div class="article-row-section">
  <div class="article-row-section-inner">
 {% load sports_tag  %}
      {% get_sports_news%}
    <h2 class="article-row-section-header">Sports News</h2>
      {% for new in sports_news %}
    <a href="{{ new.get_absolute_url }}">
      <article class="article-row">
        <div class="article-row-img">
            {% if new.thumbnail %}
          <img src="{{ new.thumbnail.url }}" alt="news" />
            {% endif %}
        </div>
        <div class="article-row-content">
          <h5 class="article-row-content-header" style="font-family: Roboto, Bold; font-size: 25px; color: blue">{{ new.title }}</h5>
            <p style="font-family:'Lato', serif; font-size: 20px; color: red">By: {{ new.writer.name }}</p>
          <p class="article-row-content-description">{{ new.summary }}</p>
        </div>
      </article>
    </a>
      {% endfor %}
  </div>
</div>
<div style="text-align:center ; font-family:'Lato', serif; font-size: 25px; color: red" >
<a href="{% url 'home:allnews' %}" class= "">View All Sports News</a>
</div>
</div>
<div class="article-row-section">
  <div class="article-row-section-inner">
 {% load opinions  %}
      {% get_opinions_news %}
    <h2 class="article-row-section-header">Opinions</h2>
      {% for new in opinions_news %}
    <a href="{{ new.get_absolute_url }}">
      <article class="article-row">
        <div class="article-row-img">
            {% if new.thumbnail %}
          <img src="{{ new.thumbnail.url }}" alt="news" />
            {% endif %}
        </div>
        <div class="article-row-content">
          <h5 class="article-row-content-header" style="font-family: Roboto, Bold; font-size: 25px; color: blue">{{ new.title }}</h5>
          <p style="font-family:'Lato', serif; font-size: 20px; color: red">By: {{ new.writer.name }}</p>
          <p class="article-row-content-description">{{ new.body|truncatewords:10 }}</p>



        </div>
      </article>
    </a>
      {% endfor %}

  </div>

</div>
<div style="text-align:center; font-family:'Lato', serif; font-size: 25px; color: red">
<a href="{% url 'home:allnews' %}" class= "">View All Opinions</a>
</div>
  <div class="content">
<div class="wording">
    {% load videos_tag %}
    {% get_latest_videos %}
<h2 style=" text-align: center; font-family:'Oswald', bold; font-size: 35px; color: black">Latest Videos</h2>
</div>
<div class="deals">
    {% for new in latest_videos %}
<div class="card">
    <a href="{{ new.url }}"><img src="{{ new.photo.url }}" /></a>
  <div class="card-section">
  <h5 style="font-family:'Ubuntu', serif; font-size: 35px; color: darkblue">{{ new.title }}</h5>
      <p style="font-family:'Lato', serif; font-size: 25px; color: dimgrey"> {{ new.summary|truncatewords:10 }}</p>
    <p style="font-family:'Lato', serif; font-size: 20px; color: red">By: {{ new.writer.name }}</p>

  </div>
</div>
    {% endfor %}
 </div>
  </div>
  <div class="content">
  <div class="wording">
    {% load events_tags %}
    {% get_latest_events %}
<h2 style=" text-align:center; font-family:'Oswald', bold; font-size: 35px; color: black">Upcoming Events</h2>
</div>
<div class="multiple-items">
    {% for new in latest_events %}
<div class="card">
    <a href="{{ new.url }}"><img src="{{ new.photo.url }}" /></a>
  <div class="card-section">
  <h5 style="font-family:'Ubuntu', serif; font-size: 35px; color: darkblue">{{ new.title }}</h5>
      <p style="font-family:'Lato', serif; font-size: 25px; color: dimgrey"> {{ new.day }}</p>
    <p style="font-family:'Lato', serif; font-size: 20px; color: red">Start: {{ new.start }}</p>
      <p style="font-family:'Lato', serif; font-size: 20px; color: red">End: {{ new.end }}</p>
  </div>
</div>
    {% endfor %}
 </div>
  </div>






 <div id="engadget-footer-social-container">
    <footer id="engadget-footer-social">
        <div class="footer-left">
		<h6 style="font-family:'Lato', serif; font-size: 20px; color: white"> Contact Us</h6>
         <h6 style="font-family:'Lato', serif; font-size: 20px; color: white">Become a partner</h6>


        </div>
        <div class="footer-right">
            <h6 style="font-family:'Lato', serif; font-size: 20px; color: white">Stay Connected</h6>
            <i class="fa fa-facebook-square fa-2x" aria-hidden="true"></i>
            <i class="fa fa-twitter-square fa-2x" aria-hidden="true"></i>
            <i class="fa fa-google-plus-square fa-2x" aria-hidden="true"></i>
            <i class="fa fa-linkedin-square fa-2x" aria-hidden="true"></i>
        </div>
    </footer>
</div>




    <script src="{% static 'js/vendor/jquery.js' %}"></script>
    <script src="{% static 'js/vendor/what-input.js' %}"></script>
    <script src="{% static 'js/vendor/foundation.js' %}"></script>
    <script src="{% static 'js/app.js' %}"></script>
  <script src="{% static 'js/' %}"></script>



  <script type="text/javascript">
    $(document).ready(function(){
      $('.multiple-items').slick({
  infinite: true,
  arrows:true,
  slidesToShow: 3,
  slidesToScroll: 1,
  dots:false,
       responsive: [
    {
      breakpoint: 1024,
      settings: {
        slidesToShow: 3,
        slidesToScroll: 3,
        infinite: true,
        dots: true
      }
    },
    {
      breakpoint: 600,
      settings: {
        slidesToShow: 2,
        slidesToScroll: 2
      }
    },
    {
      breakpoint: 480,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1
      }
    }
    // You can unslick at a given breakpoint now by adding:
    // settings: "unslick"
    // instead of a settings object
  ]

});
    });
  </script>
    <script type="text/javascript">
    $(document).ready(function(){
      $('.deals').slick({
  infinite: true,
  arrows:true,
  slidesToShow: 4,
  slidesToScroll: 1,
  dots:false,
       responsive: [
    {
      breakpoint: 1024,
      settings: {
        slidesToShow: 3,
        slidesToScroll: 3,
        infinite: true,
        dots: true
      }
    },
    {
      breakpoint: 600,
      settings: {
        slidesToShow: 2,
        slidesToScroll: 2
      }
    },
    {
      breakpoint: 480,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1
      }
    }
    // You can unslick at a given breakpoint now by adding:
    // settings: "unslick"
    // instead of a settings object
  ]

});
    });
  </script>
  </body>
</html>

home/templates/home/news.html
{% extends 'tour/main.html' %}
{% load staticfiles %}
{% block title_block %}
 {{ new.title }}
 {% endblock %}
{% block body_block %}
{% block content %}

    <div class="content">
    <div class="grid-x grid-margin-x">
        <div class="cell large-8">
<div class="flexible-article-images-container">
  <div class="flexible-article-content">
    <div class="flexible-article-image-full">
      <div class="thumbnail">
          {% if new.photo %}
        <img src="{{ new.photo.url }}" alt="">
          {% endif %}
      </div>
        <h5 style=" margin-left:10px; font-family:'Roboto', bold; font-size: 40px; color: darkblue">{{ new.title }}</h5>
      <p class="caption" style=" margin-left:10px; font-family:'Open Sans', bold; font-size: 20px; color: black">{{ new.story }}</p>
    </div>
  </div>
</div>
          <section class="tag-cloud-section">
          <h5 class="tag-cloud-title">Tags</h5>
  <div class="tag-cloud">
  <p>
      {% for tag in new.tags.all %}
    <a class="tag-cloud-individual-tag" href="{% url "home:allnews_by_tag" tag.slug %}">{{ tag.name }}</a>
{% if not forloop.last %}, {% endif %}
{% endfor %}
  </p>
  </div>
</section>




        </div>
           <div class="cell large-4">
      <div class="article-row-section">
  <div class="article-row-section-inner">

    <h2 class="article-row-section-header">Recent News</h2>
      {% for new in similar_news %}
    <a href="{{ new.get_absolute_url }}">
      <article class="article-row">
        <div class="article-row-img">
            {% if new.thumbnail %}
          <img src="{{ new.thumbnail.url }}" alt="news" />
            {% endif %}
        </div>
        <div class="article-row-content">
          <h5 class="article-row-content-header" style="font-family: Roboto, Bold; font-size: 25px; color: dimgrey">{{ new.title }}</h5>

          <p class="article-row-content-description">{{ new.body|truncatewords:8 }}</p>





        </div>
      </article>
    </a>
      {% endfor %}

  </div>

</div>
    </div>
    </div>
    </div>

{% endblock %}
{% endblock %}