apps/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from apps.sitemaps import BlogSitemap, VacancySitemap
from tour.views import travel
from home.views import index
from premise.views import premise, platia


from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

#from educa.views import CourseListView
from django.contrib.staticfiles import views

sitemaps = {
  'blogs': BlogSitemap,
  'vacancy': VacancySitemap
}

urlpatterns = [
    url(r'^$', platia, name='index'),
    url(r'^premise/', include('premise.urls')),
    url(r'^home/', include('home.urls')),
    url(r'^college/', include('college.urls')),
    #url(r'^$', CourseListView.as_view(), name='course_list'),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/logout/$', auth_views.logout, name='logout'),
    url(r'^accounts/user/login/$', auth_views.login, {'template_name': 'user_login.html'}, name='user_login'),
    url(r'^accounts/user/logout/$', auth_views.logout, {'template_name': 'user_logged_out.html'}, name='user_logout'),
    url(r'^admin/', admin.site.urls),
    #url(r'^educa/', include('educa.urls')),
    url(r'^events/', include('events.urls')),
    url(r'^tour/', include('tour.urls')),
    url(r'^student/', include('student.urls')),
    url(r'^users/', include('finders.urls')),
    url('^', include('django.contrib.auth.urls')),
    url(r'^chaining/', include('smart_selects.urls')),




    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),







]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

premise/urls.py
from django.conf.urls import url
from . import views
from .views import premise, platia, CountyAutocomplete


app_name = 'premise'
urlpatterns = [
    url(r'^premise/', premise, name='premise'),
    url(r'^allpremises/', views.all_premises, name='allpremises'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.all_premises,
          name='allpremises_by_tag'),
    url(r'^flats/', views.flat, name='flats'),
    url(r'^condos/', views.condos, name='condos'),
    url(r'^commercials/', views.commercial, name='commercials'),
    url(r'^multifamily/', views.multi_family, name='multifamily'),
    url(r'^townhouse/', views.townhouse, name='townhouses'),
    url(r'^rent/', views.rents, name='rent'),
    url(r'^buy/', views.buy, name='buy'),
    url(r'^shortstay/', views.short_stay, name='shortstay'),
    url(r'^nicosia-rent/', views.nicosia_rent, name='nicosiarent'),
    url(r'^famagusta-rent/', views.famagusta_rent, name='famagustarent'),
    url(r'^limassol-rent/', views.limassol_rent, name='limassolrent'),
    url(r'^larnaca-rent/', views.larnaca_rent, name='larnacarent'),
    url(r'^paphos-rent/', views.paphos_rent, name='paphosrent'),
    url(r'^kyrenia-rent/', views.kyrenia_rent, name='kyreniarent'),
    url(r'^nicosia-buy/', views.nicosia_buy, name='nicosiabuy'),
    url(r'^famagusta-buy/', views.famagusta_buy, name='famagustabuy'),
    url(r'^limassol-buy/', views.limassol_buy, name='limassolbuy'),
    url(r'^larnaca-buy/', views.larnaca_buy, name='larnacabuy'),
    url(r'^paphos-buy/', views.paphos_buy, name='paphosbuy'),
    url(r'^kyrenia-buy/', views.kyrenia_buy, name='kyreniabuy'),
    url(r'^nicosia-short/', views.nicosia_short, name='nicosiashort'),
    url(r'^famagusta-short/', views.famagusta_short, name='famagustashort'),
    url(r'^limassol-short/', views.limassol_short, name='limassolshort'),
    url(r'^larnaca-short/', views.larnaca_short, name='larnacashort'),
    url(r'^paphos-short/', views.paphos_short, name='paphosshort'),
    url(r'^kyrenia-short/', views.kyrenia_short, name='kyreniashort'),

    url(r'^prop/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/' 
           r'(?P<prop>[-\w]+)/$',
           views.property_detail,
           name='prop-detail'),

    url(r'^platia/', platia, name='platia'),

    url(r'^results/', views.search, name='search'),
    url(r'^mine/$', views.ManagePropertyListView.as_view(), name='my_list'),
    url(r'^create/$', views.PropertyCreateView.as_view(), name='property_add'),
    url(r'^(?P<pk>\d+)/edit/$', views.PropertyUpdateView.as_view(), name='property_edit'),
    url(r'^(?P<pk>\d+)/delete/$', views.PropertyDeleteView.as_view(), name='delete'),
    url(r'^(?P<pk>\d+)/image/$', views.PropertyImageUpdateView.as_view(), name='property_image_update'),
    url(r'^save/$', views.add_bookmark,
        name='save'),
    url(r'^my_save/$', views.BookmarkListView.as_view(), name='my_save'),
    url(r'^about-us/', views.about, name='about'),
    url(r'^dashboard/', views.dashboard, name='dashboard'),
    url(r'^message_agent/(?P<premise_id>\d+)/$', views.message_agent, name='message_agent'),
    url(r'^message/', views.message_list, name='message_list'),
    url(
        r'^county-autocomplete/$',
        CountyAutocomplete.as_view(),
        name='county-autocomplete',
    ),
    url(r'^my_services/$', views.ManageServiceListView.as_view(), name='my_services'),
    url(r'^create_service/$', views.ServiceCreateView.as_view(), name='service_add'),
    url(r'^(?P<pk>\d+)/service_edit/$', views.SericeUpdateView.as_view(), name='service_edit'),
    url(r'^(?P<pk>\d+)/delete_service/$', views.ServiceDeleteView.as_view(), name='service_delete'),
    url(r'^category/(?P<categories>[-\w]+)/$',
        views.category_detail,
        name='category-detail')
]

premise/forms.py
from django import forms
from django.forms import inlineformset_factory
from .models import Property, Image, Message, County,Service, Category
from dal import autocomplete
ImageFormSet = inlineformset_factory(Property, Image, fields=['title', 'image'], extra=3, can_delete=True)


class UserLike(forms.Form):
    premise = forms.ModelChoiceField(queryset=Property.objects.all(), widget=forms.HiddenInput)


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('name', 'phone', 'email', 'message')
        exclude = ('slug', 'premise', 'date')


class PropertyForm(forms.ModelForm):

    county = forms.ModelChoiceField(
        queryset=County.objects.all(),
        widget=autocomplete.ModelSelect2(url='premise:county-autocomplete')
    )

    class Meta:
        model = Property
        fields = ('price', 'county', 'type', 'bathrooms', 'bedrooms', 'name', 'amenities', 'purpose', 'details', 'key_features',
              'slug', 'tags', 'size', 'agent')


class ServiceForm(forms.ModelForm):
    categories = forms.ModelMultipleChoiceField(queryset=Category.objects.all(), widget=forms.CheckboxSelectMultiple())

    class Meta:
        model = Service
        fields = ('name', 'photo', 'county', 'ward', 'location', 'phone', 'price', 'tag_line', 'detail', 'categories'

                  )

premise/views.py
from django.shortcuts import render, get_object_or_404
from .models import Property, Profile, Type, Image, Liked, Bookmark, Message, County, Service, Category
from taggit.models import Tag
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count, When, Value, Case, PositiveSmallIntegerField
from .filters import PropertyFilter
from django.core.urlresolvers import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from braces.views import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import redirect, get_object_or_404
from .forms import ImageFormSet, MessageForm, PropertyForm, ServiceForm
from django.views.generic.base import TemplateResponseMixin, View
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from finders.decorators import finder_required, profile_required
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django_ajax.decorators import ajax
from dal import autocomplete


def premise(request):
    return render(request, 'premise/index.html')


def all_premises(request, tag_slug=None):
    premises = Property.objects.all().order_by('sponsored')
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        premises = premises.filter(tags__in=[tag])
    total_premises = premises.count()
    paginator = Paginator(premises, 2)
    page = request.GET.get('page')
    try:
        premises = paginator.page(page)
    except PageNotAnInteger:
        premises = paginator.page(1)
    except EmptyPage:
        premises = paginator.page(paginator.num_pages)
    return render(request, 'premise/property.html', {'premises': premises, 'page': page, 'tag': tag, 'total_premises': total_premises })


def flat(request, tag_slug=None):
    premises = Property.objects.filter(type='flat')
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        premises = premises.filter(tags__in=[tag])
    total_premises = premises.count()
    paginator = Paginator(premises, 2)
    page = request.GET.get('page')
    try:
        premises = paginator.page(page)
    except PageNotAnInteger:
        premises = paginator.page(1)
    except EmptyPage:
        premises = paginator.page(paginator.num_pages)
    return render(request, 'premise/property.html', {'premises': premises, 'page': page, 'tag': tag , 'total_premises': total_premises})


def condos(request, tag_slug=None):
    premises = Property.objects.filter(type='condo').order_by('sponsored')
    total_premises = premises.count()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        premises = premises.filter(tags__in=[tag])
    total_premises = premises.count()
    paginator = Paginator(premises, 2)
    page = request.GET.get('page')
    try:
        premises = paginator.page(page)
    except PageNotAnInteger:
        premises = paginator.page(1)
    except EmptyPage:
        premises = paginator.page(paginator.num_pages)
    return render(request, 'premise/property.html', {'premises': premises, 'page': page, 'tag': tag, 'total_premises': total_premises})


def commercial(request, tag_slug=None):
    premises = Property.objects.filter(type='commercial').order_by('sponsored')
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        premises = premises.filter(tags__in=[tag])
    total_premises = premises.count()
    paginator = Paginator(premises, 2)
    page = request.GET.get('page')
    try:
        premises = paginator.page(page)
    except PageNotAnInteger:
        premises = paginator.page(1)
    except EmptyPage:
        premises = paginator.page(paginator.num_pages)
    return render(request, 'premise/property.html', {'premises': premises, 'page': page, 'tag': tag,  'total_premises': total_premises})


def townhouse(request, tag_slug=None):
    premises = Property.objects.filter(type='townhouse').order_by('sponsored')
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        premises = premises.filter(tags__in=[tag])
    total_premises = premises.count()

    paginator = Paginator(premises, 2)
    page = request.GET.get('page')
    try:
        premises = paginator.page(page)
    except PageNotAnInteger:
        premises = paginator.page(1)
    except EmptyPage:
        premises = paginator.page(paginator.num_pages)
    return render(request, 'premise/property.html', {'premises': premises, 'page': page, 'tag': tag, 'total_premises': total_premises})


def multi_family(request, tag_slug=None):
    premises = Property.objects.filter(type='multifamily').order_by('sponsored')
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        premises = premises.filter(tags__in=[tag])
    total_premises = premises.count()
    paginator = Paginator(premises, 2)
    page = request.GET.get('page')
    try:
        premises = paginator.page(page)
    except PageNotAnInteger:
        premises = paginator.page(1)
    except EmptyPage:
        premises = paginator.page(paginator.num_pages)
    return render(request, 'premise/property.html', {'premises': premises, 'page': page, 'tag': tag , 'total_premises': total_premises})


def rents(request, tag_slug=None):
    premises = Property.objects.filter(purpose='rent').order_by('sponsored')
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        premises = premises.filter(tags__in=[tag])
    total_premises = premises.count()

    paginator = Paginator(premises, 2)
    page = request.GET.get('page')
    try:
        premises = paginator.page(page)
    except PageNotAnInteger:
        premises = paginator.page(1)
    except EmptyPage:
        premises = paginator.page(paginator.num_pages)
    return render(request, 'premise/property.html', {'premises': premises, 'page': page, 'tag': tag, 'total_premises': total_premises})


def buy(request, tag_slug=None):
    premises = Property.objects.filter(purpose='buy').order_by('sponsored')
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        premises = premises.filter(tags__in=[tag])
    total_premises = premises.count()
    paginator = Paginator(premises, 20)
    page = request.GET.get('page')
    try:
        premises = paginator.page(page)
    except PageNotAnInteger:
        premises = paginator.page(1)
    except EmptyPage:
        premises = paginator.page(paginator.num_pages)
    return render(request, 'premise/property.html', {'premises': premises, 'page': page, 'tag': tag, 'total_premises': total_premises})


def short_stay(request, tag_slug=None):
    premises = Property.objects.filter(purpose='short_stay').order_by('sponsored')
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        premises = premises.filter(tags__in=[tag])
    total_premises = premises.count()
    paginator = Paginator(premises, 20)
    page = request.GET.get('page')
    try:
        premises = paginator.page(page)
    except PageNotAnInteger:
        premises = paginator.page(1)
    except EmptyPage:
        premises = paginator.page(paginator.num_pages)
    return render(request, 'premise/property.html', {'premises': premises, 'page': page, 'tag': tag, 'total_premises': total_premises})


def property_detail(request, year, month, day, prop):
    prop = get_object_or_404(Property, slug=prop)
    image = Image.objects.filter(property=prop)
    prop_tag_ids = prop.tags.values_list('id', flat=True)
    similar_props = Property.objects.filter(tags__in=prop_tag_ids).exclude(id=prop.id)
    similar_props = similar_props.annotate(same_tags=Count('tags')).order_by('-same_tags', '-created')[:5]
    return render(request, 'premise/property_detail.html', {'prop': prop, 'image': image, 'similar_props': similar_props})


def platia(request):
    f = PropertyFilter(request.GET, queryset=Property.objects.all())
    return render(request, 'premise/search.html', {'filter': f})


def search(request, tag_slug=None):
    f = PropertyFilter(request.GET, queryset=Property.objects.all())
    premises = f.qs
    total_premises = premises.count()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        f = premises.filter(tags__in=[tag])

    paginator = Paginator(f.qs, 3)
    page = request.GET.get('page')
    try:
        premises = paginator.page(page)
    except PageNotAnInteger:
        premises = paginator.page(1)
    except EmptyPage:
        premises = paginator.page(paginator.num_pages)
    return render(request, 'premise/property.html', {'premises': premises, 'page': page, 'tag': tag, 'filter': f, 'total_premises': total_premises})


@method_decorator([login_required, profile_required], name='dispatch')
class PropertyListView(ListView):
    model = Property
    template_name = 'premise/my_list.html'

    def get_queryset(self):
        qs = super(PropertyListView, self).get_queryset()
        return qs.filter(agent=self.request.user)


class AgentMixin(object):
    def get_queryset(self):
        qs = super(AgentMixin, self).get_queryset()
        return qs.filter(agent=self.request.user)


class AgentEditMixin(object):
    def form_valid(self, form):
        form.instance.agent = self.request.user
        return super(AgentEditMixin, form).form_valid(form)


class AgentPropertyMixin(AgentMixin, LoginRequiredMixin):
    model = Property

    success_url = reverse_lazy('premise:my_list')


class AgentPropertyEditMixin(AgentPropertyMixin, AgentEditMixin):


    template_name = 'premise/form.html'


@method_decorator([login_required, profile_required], name='dispatch')
class ManagePropertyListView(AgentPropertyMixin, ListView):
    template_name = 'premise/my_list.html'

premise/templates/premise/dashboard.html
{% extends 'tour/main.html' %}
{% load staticfiles %}
{% block title %}Dashboard{% endblock %}
{% block body_block %}

{% block content %}
    <div class="grid-container">
<h5 class="center" style=" margin-top: 1.5%; margin-bottom: 0.001%; font-family: 'Oswald',Bold; font-size: 40px; text-align: center; color: darkred">My  listing </h5>

     <table id="vertical" style="width: 75%">

   <tr>
          <th style="font-family: Oswald ,bold; color: darkblue; padding: 5px; border: 1px solid black;border-collapse: collapse; text-align: left">My property listing</th>
           <td style="border-collapse: collapse; border: 1px solid black; padding: 5px; text-align: left; width: 50%"> <h5 style="font-family: Merriweather, serif; font-weight: bold; font-size: 15px; color: red; text-align: center">
<a href="{% url 'premise:property_add'  %}"><i class="fa fa-plus " style="color:#002C3E" aria-hidden="true"></i>Add</a>&#8226;
    <a href="{% url 'premise:my_list'  %}"><i class="fa fa-pencil " style="color:#002C3E" aria-hidden="true"></i>Change</a>
</h5></td>
       </tr>
   <tr>
       <tr>
         <th style="font-family: Oswald ,bold; color: darkblue; padding: 5px; border: 1px solid black;border-collapse: collapse; text-align: left">My services Listing</th>
           <td style="border-collapse: collapse; border: 1px solid black; padding: 5px; text-align: left; width: 50%"> <h5 style="font-family: Merriweather, serif; font-weight: bold; font-size: 15px; color: red; text-align: center">
<a href="{% url 'premise:service_add'  %}"><i class="fa fa-plus " style="color:#002C3E" aria-hidden="true"></i> Add</a>&#8226;
    <a href="{% url 'premise:my_services'  %}"><i class="fa fa-pencil " style="color:#002C3E" aria-hidden="true"></i>Change</a>
</h5></td>
       </tr>


   </table>
    </div>
{% endblock %}
{% endblock %}

premise/templates/premise/my_list.html
{% extends 'tour/main.html' %}
{% load staticfiles %}
{% block title_block %}
    Properties
    {% endblock %}
{% block body_block %}

{% block content %}
<h5 class="center" style=" margin-top: 1.5%; margin-bottom: 0.001%; font-family: 'Oswald',Bold; font-size: 40px; text-align: center; color: darkred">My Property List</h5>
{% if object_list %}
   <h5>{{ object_list.count }} Home{{ premises|pluralize }}</h5>
<table>
<thead>
<tr style="font-family: Oswald, bold; color: darkblue">
    <th width="100">Name</th>
    <th width="50">District</th>
    <th width="50">Purpose</th>
    <th width="50">Category</th>
    <th width="50">Price</th>
    <th width="10">Bedrooms</th>
    <th width="10">Bathrooms</th>
    <th width="50">Make Changes</th>

</tr>

</thead>
<tbody>
{% for premise in object_list %}
<tr>
  <td width="100">{{ premise.name }}</td>
<td>{{ premise.district|capfirst }}</td>
<td>{{ premise.purpose|capfirst }}</td>
<td>{{ premise.type|capfirst }}</td>
<td>{{ premise.price }}</td>
<td width="10">{{  premise.bedrooms }}</td>
<td width="10">{{ premise.bathrooms }}</td>
<td> <p style="font-family: Merriweather, serif; font-weight: bold; font-size: 18px; color: red; text-align: justify">
<a href="{% url "premise:property_edit" premise.id %}">Edit <i class="fa fa-edit " style="color:#002C3E" aria-hidden="true"></i></a>&#8226;
<a href="{% url 'premise:delete' premise.id %}">Delete <i class="fa fa-remove " style="color:#002C3E" aria-hidden="true"></i></a>&#8226;
    <a href="{% url "premise:property_image_update" premise.id %}">Edit Images <i class="fa fa-image " style="color:#002C3E" aria-hidden="true"></i></a>
</p></td>
</tr>
{% endfor %}
</tbody>
</table>

{% else %}
<h5 style="text-align: center">Add your first property</h5>
{% endif %}



     {% if page_obj.has_other_pages %}
    <ul class="pagination-pointed pagination text-center" role="navigation" aria-label="Pagination">
    {% if page_obj.has_previous %}
        <li class="pagination-previous"><a class="pagination-pointed-button" href="?page={{ page_obj.previous_page_number }}" >Previous <span class="show-for-sr">Page</span></a></li>
        {% else %}
  <li class="pagination-previous disabled">Previous <span class="show-for-sr">Page</span></li>
        {% endif %}
    {% for i in  page_obj.paginator.page_range %}
    {% if page_obj.number == i %}
  <li class="current"><span class="show-for-sr">You're on page</span> {{ i }}</li>
        {% else %}
  <li><a class="pagination-pointed-button" href="?page={{ i }}" aria-label="Page 2">{{ i }}</a></li>
  {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
  <li class="pagination-next"><a class="pagination-pointed-button" href="?page={{ page_obj.next_page_number }}" aria-label="Next page">Next <span class="show-for-sr">page</span></a></li>
        {% endif %}
</ul>
    {% endif %}
    <div class="grid-container">
    <a href="{% url 'premise:property_add' %}" class="button expanded" style="text-align: center">
    Add A New Property
    </a>
    </div>
    {% if tag.name in tag %}
        {% if object_list.has_other_pages %}
    <ul class="pagination-pointed pagination text-center" role="navigation" aria-label="Pagination">
    {% if object_list.has_previous %}
        <li class="pagination-previous"><a class="pagination-pointed-button" href="?page={{ object_list.previous_page_number }}" >Previous <span class="show-for-sr">Page</span></a></li>
        {% else %}
  <li class="pagination-previous disabled">Previous <span class="show-for-sr">Page</span></li>
        {% endif %}
    {% for i in  object_list.paginator.page_range %}
    {% if object_list.number == i %}
  <li class="current"><span class="show-for-sr">You're on page</span> {{ i }}</li>
        {% else %}
  <li><a class="pagination-pointed-button" href="?page={{ i }}" aria-label="Page 2">{{ i }}</a></li>
  {% endif %}
    {% endfor %}
    {% if object_list.has_next %}
  <li class="pagination-next"><a class="pagination-pointed-button" href="?page={{ object_list.next_page_number }}" aria-label="Next page">Next <span class="show-for-sr">page</span></a></li>
        {% endif %}
</ul>
    {% endif %}
    {% endif %}
{% endblock %}

{% endblock %}

premise/templates/premise/my_services.html
{% extends 'tour/main.html' %}
{% load staticfiles %}
{% block title_block %}
    Properties
    {% endblock %}
{% block body_block %}

{% block content %}
<h5 class="center" style=" margin-top: 1.5%; margin-bottom: 0.001%; font-family: 'Oswald',Bold; font-size: 40px; text-align: center; color: darkred">My Service List</h5>
{% if object_list %}
   <h5>{{ object_list.count }} Service{{ services|pluralize }}</h5>
<table>
<thead>
<tr style="font-family: Oswald, bold; color: darkblue">
    <th width="100">Name</th>
    <th width="50">County</th>
    <th width="50">Ward</th>
    <th width="50">Tagline</th>
    <th width="50">Phone</th>
    <th width="10">Location</th>
    <th width="10">Price</th>
    <th width="50">Make Changes</th>

</tr>

</thead>
<tbody>
{% for service in object_list %}
<tr>
  <td width="100">{{ service.name }}</td>
<td>{{ service.county|capfirst }}</td>
<td>{{ service.ward|capfirst }}</td>
<td>{{ service.tag_line|capfirst }}</td>
<td>{{ service.phone }}</td>
<td width="10">{{  service.location }}</td>
<td width="10">{{ service.price }}</td>
<td> <p style="font-family: Merriweather, serif; font-weight: bold; font-size: 18px; color: red; text-align: justify">
<a href="{% url "premise:service_edit" service.id %}">Edit <i class="fa fa-edit " style="color:#002C3E" aria-hidden="true"></i></a>&#8226;
<a href="{% url 'premise:service_delete' service.id %}">Delete <i class="fa fa-remove " style="color:#002C3E" aria-hidden="true"></i></a>&#8226;
    <a href="">Edit Images <i class="fa fa-image " style="color:#002C3E" aria-hidden="true"></i></a>
</p></td>
</tr>
{% endfor %}
</tbody>
</table>

{% else %}
<h5 style="text-align: center">Add your first service</h5>
{% endif %}



     {% if page_obj.has_other_pages %}
    <ul class="pagination-pointed pagination text-center" role="navigation" aria-label="Pagination">
    {% if page_obj.has_previous %}
        <li class="pagination-previous"><a class="pagination-pointed-button" href="?page={{ page_obj.previous_page_number }}" >Previous <span class="show-for-sr">Page</span></a></li>
        {% else %}
  <li class="pagination-previous disabled">Previous <span class="show-for-sr">Page</span></li>
        {% endif %}
    {% for i in  page_obj.paginator.page_range %}
    {% if page_obj.number == i %}
  <li class="current"><span class="show-for-sr">You're on page</span> {{ i }}</li>
        {% else %}
  <li><a class="pagination-pointed-button" href="?page={{ i }}" aria-label="Page 2">{{ i }}</a></li>
  {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
  <li class="pagination-next"><a class="pagination-pointed-button" href="?page={{ page_obj.next_page_number }}" aria-label="Next page">Next <span class="show-for-sr">page</span></a></li>
        {% endif %}
</ul>
    {% endif %}
    <div class="grid-container">
    <a href="{% url 'premise:service_add' %}" class="button expanded" style="text-align: center">
    Add A New Property
    </a>
    </div>
    {% if tag.name in tag %}
        {% if object_list.has_other_pages %}
    <ul class="pagination-pointed pagination text-center" role="navigation" aria-label="Pagination">
    {% if object_list.has_previous %}
        <li class="pagination-previous"><a class="pagination-pointed-button" href="?page={{ object_list.previous_page_number }}" >Previous <span class="show-for-sr">Page</span></a></li>
        {% else %}
  <li class="pagination-previous disabled">Previous <span class="show-for-sr">Page</span></li>
        {% endif %}
    {% for i in  object_list.paginator.page_range %}
    {% if object_list.number == i %}
  <li class="current"><span class="show-for-sr">You're on page</span> {{ i }}</li>
        {% else %}
  <li><a class="pagination-pointed-button" href="?page={{ i }}" aria-label="Page 2">{{ i }}</a></li>
  {% endif %}
    {% endfor %}
    {% if object_list.has_next %}
  <li class="pagination-next"><a class="pagination-pointed-button" href="?page={{ object_list.next_page_number }}" aria-label="Next page">Next <span class="show-for-sr">page</span></a></li>
        {% endif %}
</ul>
    {% endif %}
    {% endif %}
{% endblock %}

{% endblock %}