apps/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from apps.sitemaps import BlogSitemap, VacancySitemap
from tour.views import travel
from home.views import index
from premise.views import premise, platia


from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

#from educa.views import CourseListView
from django.contrib.staticfiles import views

sitemaps = {
  'blogs': BlogSitemap,
  'vacancy': VacancySitemap
}

urlpatterns = [
    url(r'^$', platia, name='index'),
    url(r'^premise/', include('premise.urls')),
    url(r'^home/', include('home.urls')),
    url(r'^college/', include('college.urls')),
    #url(r'^$', CourseListView.as_view(), name='course_list'),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/logout/$', auth_views.logout, name='logout'),
    url(r'^accounts/user/login/$', auth_views.login, {'template_name': 'user_login.html'}, name='user_login'),
    url(r'^accounts/user/logout/$', auth_views.logout, {'template_name': 'user_logged_out.html'}, name='user_logout'),
    url(r'^admin/', admin.site.urls),
    #url(r'^educa/', include('educa.urls')),
    url(r'^events/', include('events.urls')),
    url(r'^tour/', include('tour.urls')),
    url(r'^student/', include('student.urls')),
    url(r'^users/', include('finders.urls')),
    url('^', include('django.contrib.auth.urls')),
    url(r'^chaining/', include('smart_selects.urls')),




    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),







]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

platia/urls.py
from django.conf.urls import url
from . import views
from .views import travel


app_name = 'tour'
urlpatterns = [



    url(r'^travel/', travel, name='travel'),
    url(r'^alltrips/', views.alltrips, name='alltrips'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.alltrips,
          name='alltrips_by_tag'),
    url(r'^trip/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/' \
           r'(?P<trip>[-\w]+)/$',
           views.trip_detail,
           name='trip-detail'),

]

platia/models.py
from __future__ import unicode_literals
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager

from django.db import models


class Category(models.Model):

    title = models.CharField(max_length=50)
    detail = models.TextField(blank=True)
    date_added = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-date_added',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title


class Trip(models.Model):
    AVAILABILITY = (
        ('yes', 'YES'),
        ('no', 'NO'))
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=250, unique_for_date='date_added', default='trips')
    date_added = models.DateTimeField(auto_now=True)
    price = models.DecimalField(max_digits=11, decimal_places=2)
    detail = models.TextField()
    start = models.DateField(blank=True)
    End = models.DateField(blank=True)
    summary = models.TextField()
    category = models.ForeignKey(Category)
    included = models.TextField()
    excluded = models.TextField()
    availability = models.CharField(max_length=50, choices=AVAILABILITY, default='no')
    photo = ProcessedImageField(upload_to='trips', processors=[ResizeToFill(1778, 1000)],
                                format='JPEG',
                                options={'quality': 100}, blank=True)
    tags = TaggableManager()


    class Meta:
        ordering = ('-date_added',)
        verbose_name_plural = 'Trips'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('tour:trip-detail', args=[self.date_added.year,
                                                   self.date_added.strftime('%m'),
                                                   self.date_added.strftime('%d'),
                                                   self.slug])


class Image(models.Model):
    title = models.CharField(max_length=100)
    date_added = models.DateTimeField(auto_now=True)
    image = ProcessedImageField(upload_to='images', processors=[ResizeToFill(1024, 767)],
                                format='JPEG',
                                options={'quality': 100})
    trip = models.ForeignKey(Trip, related_name='images')

    class Meta:
        ordering = ('-date_added',)

    def __str__(self):
        return self.title

platia/views.py
from django.shortcuts import render, get_object_or_404
from .models import Trip, Image
from taggit.models import Tag
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count


def travel(request):
    return render(request, 'tour/index.html')


def alltrips(request, tag_slug=None):
    trips = Trip.objects.all().order_by('-date_added')
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        trips = trips.filter(tags__in=[tag])

    paginator = Paginator(trips, 6)
    page = request.GET.get('page')
    try:
        trips = paginator.page(page)
    except PageNotAnInteger:
        trips = paginator.page(1)
    except EmptyPage:
        trips = paginator.page(paginator.num_pages)
    return render(request, 'tour/trips/alltrips.html', {'trips': trips, 'page': page, 'tag': tag})


def trip_detail(request, year, month, day, trip):
    trip = get_object_or_404(Trip, slug=trip)
    image = Image.objects.filter(trip=trip)
    trip_tag_ids = trip.tags.values_list('id', flat=True)
    similar_trips = Trip.objects.filter(tags__in=trip_tag_ids).exclude(id=trip.id)
    similar_trips = similar_trips.annotate(same_tags=Count('tags')).order_by('-same_tags', '-date_added')[:5]
    return render(request, 'tour/trips/trip_detail.html', {'trip': trip, 'image': image, 'similar_trips': similar_trips})

platia/templates/tour/trips/alltrips.html
{% extends 'tour/main.html' %}
{% load staticfiles %}
{% block title_block %}
    Trips
    {% endblock %}
{% block body_block %}

{% block content %}
<h5 class="center" style=" margin-top: 1.5%; margin-bottom: 0.001%; font-family: 'Oswald',Bold; font-size: 40px">ALL TRIPS</h5>
{% if trips %}

{% if tag %}
<h2>Trip tagged with "{{ tag.name }}"</h2>
{% endif %}

 <div class="contain">
<div class="grid-x grid-margin-x">
       {% for trip in trips %}
        <div class="cell large-3">
        <div class="news-card-tag">

  <p class="tags">
      Tags:
      {% for tag in trip.tags.all %}
          <span class="label"><a href="{% url "tour:alltrips_by_tag" tag.slug %}">{{ tag.name }}</a>
          </span>

{% if not forloop.last %}, {% endif %}
{% endfor %}
</p>
</div>

<div class="card news-card">
{% if trip.photo %}
    <img src="{{ trip.photo.url }}">
    {% endif %}
  <div class="card-section">

    <article class="news-card-article">
      <h4 class="news-card-titl" style="font-family: Roboto; font-size: 35px; color: darkblue"><a href="{{ trip.get_absolute_url }}">{{ trip.title }}</a></h4>
        <p class="news-card-description" style="font-family: Lato; font-size: 25px; color: dimgrey">Ksh {{ trip.detail|truncatechars:10}}</p>
      <p class="news-card-descriptio" style="font-family: Ubuntu; font-size: 25px; color: dimgrey">Ksh {{ trip.price}}</p>
        <p class="news-card-descriptio" style="font-family: Roboto; font-size: 20px; color: dimgrey">Add To Favourites <i class="fa fa-heart  " style="color:red" aria-hidden="true"></i></p>
    </article>

</div>


</div>
    </div>
{% endfor %}
</div>
</div>

{% else %}
<p>No trips yet</p>
{% endif %}

    {% if trips.has_other_pages %}
    <ul class="pagination-pointed pagination text-center" role="navigation" aria-label="Pagination">
    {% if trips.has_previous %}
        <li class="pagination-previous"><a class="pagination-pointed-button" href="?page={{ trips.previous_page_number }}" >Previous <span class="show-for-sr">Page</span></a></li>
        {% else %}
  <li class="pagination-previous disabled">Previous <span class="show-for-sr">Page</span></li>
        {% endif %}
    {% for i in  trips.paginator.page_range %}
    {% if trips.number == i %}
  <li class="current"><span class="show-for-sr">You're on page</span> {{ i }}</li>
        {% else %}
  <li><a class="pagination-pointed-button" href="?page={{ i }}" aria-label="Page 2">{{ i }}</a></li>
  {% endif %}
    {% endfor %}
    {% if trips.has_next %}
  <li class="pagination-next"><a class="pagination-pointed-button" href="?page={{ trips.next_page_number }}" aria-label="Next page">Next <span class="show-for-sr">page</span></a></li>
        {% endif %}
</ul>
    {% endif %}
    {% if tag.name in tag %}
        {% if trips.has_other_pages %}
    <ul class="pagination-pointed pagination text-center" role="navigation" aria-label="Pagination">
    {% if trips.has_previous %}
        <li class="pagination-previous"><a class="pagination-pointed-button" href="?page={{ trips.previous_page_number }}" >Previous <span class="show-for-sr">Page</span></a></li>
        {% else %}
  <li class="pagination-previous disabled">Previous <span class="show-for-sr">Page</span></li>
        {% endif %}
    {% for i in  trips.paginator.page_range %}
    {% if trips.number == i %}
  <li class="current"><span class="show-for-sr">You're on page</span> {{ i }}</li>
        {% else %}
  <li><a class="pagination-pointed-button" href="?page={{ i }}" aria-label="Page 2">{{ i }}</a></li>
  {% endif %}
    {% endfor %}
    {% if trips.has_next %}
  <li class="pagination-next"><a class="pagination-pointed-button" href="?page={{ trips.next_page_number }}" aria-label="Next page">Next <span class="show-for-sr">page</span></a></li>
        {% endif %}
</ul>
    {% endif %}
    {% endif %}





{% endblock %}

{% endblock %}

platia/templates/tour/trips/trip_detail.html
{% extends 'tour/main.html' %}
{% load staticfiles %}
{% block content %}
<div class="grid-container">
<div class="grid-x grid-margin-x">
<div class="cell large-8 small-12 medium-12">
<div class="fullscreen-image-slider">
  <div class="orbit" role="region" aria-label="FullScreen Pictures" data-orbit>
    <ul class="orbit-container">

      <button class="orbit-previous">

        <span class="show-for-sr">Previous Slide</span>
        <span class="nav fa fa-chevron-left fa-3x"></span>
      </button>

      <button class="orbit-next">
        <span class="show-for-sr">Next Slide</span>
        <span class="nav fa fa-chevron-right fa-3x"></span>
      </button>
        {% if image %}
            {% for img in image %}
      <li class="is-active orbit-slide">
        <img class="orbit-image" src="{{ img.image.url }}" alt="photo">
        <figcaption class="orbit-caption">
          <h1></h1>
        </figcaption>
      </li>
            {% endfor %}
        {% endif %}
    </ul>
  </div>
  </div>
    <div class="descip" style="padding:20px;">
<h1 style=" font-family:'Ubuntu', serif; font-size: 40px; color: red">{{ trip.title }} Kshs {{ trip.price }}</h1>
<a href="#features" class= "hollow button large">Add to Favourites<i class="fa fa-star " style="color:red" aria-hidden="true"></i></a>
<a href="#features" class= "button large">Book Now</a>
<h1 style="font-family:'Chela', serif; font-size: 30px; color: darkblue">Description</h1>
<p  style="font-family:'Roboto', serif; font-size: 20px; color: black">
{{ trip.detail }}
</p>
    </div>

</div>
<div class="cell large-4">
<div class="trips" style="padding:20px;">

<h1 style="padding:20px; font-family:'Ubuntu', serif; font-size: 30px; color: darkblue">Included</h1>

<pre style=" font-family:'Lato', serif; font-size: 25px; color: black;white-space: pre-wrap;word-wrap: break-word; text-align: justify">
{{ trip.included }}
</pre>

<h1 style="padding:20px; font-family:'Ubuntu', serif; font-size: 30px; color: darkblue">Excluded</h1>
<pre style=" font-family:'Lato', serif; font-size: 25px; color: black;white-space: pre-wrap;word-wrap: break-word; text-align: justify">
{{ trip.excluded }}
</pre>
</div>
</div>
</div>
</div>
    <div class="content">
<div class="wording">


<h2 style=" margin-left:10px; font-family:'Roboto', bold; font-size: 30px; color: black">Recommended Trips for You</h2>
</div>

<div class="responsive">
    {% for trip in similar_trips %}
<div class="card">
<a href="{{ trip.get_absolute_url }}">
         <img src="{{ trip.photo.url }}" /></a>
  <div class="card-section">
  <h5 style="font-family:'Playfair Display', serif; font-size: 20px; color: black">{{ trip.title }}</h5>
    <p style="font-family:'Playfair Display', serif; font-size: 20px; color: red">{{ trip.price }}</p>
  </div>
</div>
    {% endfor %}





 </div>
    </div>


{% endblock %}

platia/templates/tour/trips/trips.html
{% extends 'tour/main.html' %}
{% load staticfiles %}
{% block title_block %}
    Trips
    {% endblock %}
{% block body_block %}

{% block content %}
<h5 class="center" style=" margin-top: 1.5%; margin-bottom: 0.001%; font-family: 'Oswald',Bold; font-size: 40px">ALL TRIPS</h5>
{% if trips %}

{% if tag %}
<h2>Trip tagged with "{{ tag.name }}"</h2>
{% endif %}

 <div class="contain">
<div class="grid-x grid-margin-x">
       {% for trip in trips %}
        <div class="cell large-3">
        <div class="news-card-tag">

  <p class="tags">
      Tags:
      {% for tag in trip.tags.all %}
          <span class="label"><a href="{% url "tour:alltrips_by_tag" tag.slug %}">{{ tag.name }}</a>
          </span>

{% if not forloop.last %}, {% endif %}
{% endfor %}
</p>
</div>

<div class="card news-card">
{% if trip.photo %}
    <img src="{{ trip.photo.url }}">
    {% endif %}
  <div class="card-section">
    <div class="news-card-date">{{ trip.date_added }}</div>
    <article class="news-card-article">
      <h4 class="news-card-title"><a href="{{ trip.get_absolute_url }}">{{ trip.title }}</a></h4>
      <p class="news-card-description">{{ trip.detail|truncatewords:10 }}</p>
    </article>

</div>
</div>
    </div>
{% endfor %}
</div>
</div>
{% else %}
<p>No trips yet</p>
{% endif %}
{% endblock %}

{% endblock %}