apps/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from apps.sitemaps import BlogSitemap, VacancySitemap
from tour.views import travel
from home.views import index
from premise.views import premise, platia


from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

#from educa.views import CourseListView
from django.contrib.staticfiles import views

sitemaps = {
  'blogs': BlogSitemap,
  'vacancy': VacancySitemap
}

urlpatterns = [
    url(r'^$', platia, name='index'),
    url(r'^premise/', include('premise.urls')),
    url(r'^home/', include('home.urls')),
    url(r'^college/', include('college.urls')),
    #url(r'^$', CourseListView.as_view(), name='course_list'),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/logout/$', auth_views.logout, name='logout'),
    url(r'^accounts/user/login/$', auth_views.login, {'template_name': 'user_login.html'}, name='user_login'),
    url(r'^accounts/user/logout/$', auth_views.logout, {'template_name': 'user_logged_out.html'}, name='user_logout'),
    url(r'^admin/', admin.site.urls),
    #url(r'^educa/', include('educa.urls')),
    url(r'^events/', include('events.urls')),
    url(r'^tour/', include('tour.urls')),
    url(r'^student/', include('student.urls')),
    url(r'^users/', include('finders.urls')),
    url('^', include('django.contrib.auth.urls')),
    url(r'^chaining/', include('smart_selects.urls')),




    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),







]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finders/urls.py
from django.conf.urls import url
from . import views
app_name = 'finders'


urlpatterns = [
    url(r'^user_register/$', views.FinderRegistrationView.as_view(), name='user_registration'),
    url(r'^agent_register/$', views.AgentRegistrationView.as_view(), name='agent_registration'),
    url(r'^common/$', views.common_view, name='common'),
    url(r'^edit/$', views.edit, name='edit'),
    url(r'^profile/$', views.profile, name='profile'),
]

home/urls.py
from . import views
from django.conf.urls import url
from .views import index


app_name = 'home'
urlpatterns = [
         url(r'^$', index, name='index'),
         url(r'^allnews/', views.allnews, name='allnews'),
         url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.allnews,
          name='allnews_by_tag'),
         url(r'^new/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/' \
           r'(?P<new>[-\w]+)/$',
           views.latest_detail,
           name='news'),
         ]

platia/urls.py
from django.conf.urls import url
from . import views
from .views import travel


app_name = 'tour'
urlpatterns = [



    url(r'^travel/', travel, name='travel'),
    url(r'^alltrips/', views.alltrips, name='alltrips'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.alltrips,
          name='alltrips_by_tag'),
    url(r'^trip/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/' \
           r'(?P<trip>[-\w]+)/$',
           views.trip_detail,
           name='trip-detail'),

]

premise/urls.py
from django.conf.urls import url
from . import views
from .views import premise, platia, CountyAutocomplete


app_name = 'premise'
urlpatterns = [
    url(r'^premise/', premise, name='premise'),
    url(r'^allpremises/', views.all_premises, name='allpremises'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.all_premises,
          name='allpremises_by_tag'),
    url(r'^flats/', views.flat, name='flats'),
    url(r'^condos/', views.condos, name='condos'),
    url(r'^commercials/', views.commercial, name='commercials'),
    url(r'^multifamily/', views.multi_family, name='multifamily'),
    url(r'^townhouse/', views.townhouse, name='townhouses'),
    url(r'^rent/', views.rents, name='rent'),
    url(r'^buy/', views.buy, name='buy'),
    url(r'^shortstay/', views.short_stay, name='shortstay'),
    url(r'^nicosia-rent/', views.nicosia_rent, name='nicosiarent'),
    url(r'^famagusta-rent/', views.famagusta_rent, name='famagustarent'),
    url(r'^limassol-rent/', views.limassol_rent, name='limassolrent'),
    url(r'^larnaca-rent/', views.larnaca_rent, name='larnacarent'),
    url(r'^paphos-rent/', views.paphos_rent, name='paphosrent'),
    url(r'^kyrenia-rent/', views.kyrenia_rent, name='kyreniarent'),
    url(r'^nicosia-buy/', views.nicosia_buy, name='nicosiabuy'),
    url(r'^famagusta-buy/', views.famagusta_buy, name='famagustabuy'),
    url(r'^limassol-buy/', views.limassol_buy, name='limassolbuy'),
    url(r'^larnaca-buy/', views.larnaca_buy, name='larnacabuy'),
    url(r'^paphos-buy/', views.paphos_buy, name='paphosbuy'),
    url(r'^kyrenia-buy/', views.kyrenia_buy, name='kyreniabuy'),
    url(r'^nicosia-short/', views.nicosia_short, name='nicosiashort'),
    url(r'^famagusta-short/', views.famagusta_short, name='famagustashort'),
    url(r'^limassol-short/', views.limassol_short, name='limassolshort'),
    url(r'^larnaca-short/', views.larnaca_short, name='larnacashort'),
    url(r'^paphos-short/', views.paphos_short, name='paphosshort'),
    url(r'^kyrenia-short/', views.kyrenia_short, name='kyreniashort'),

    url(r'^prop/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/' 
           r'(?P<prop>[-\w]+)/$',
           views.property_detail,
           name='prop-detail'),

    url(r'^platia/', platia, name='platia'),

    url(r'^results/', views.search, name='search'),
    url(r'^mine/$', views.ManagePropertyListView.as_view(), name='my_list'),
    url(r'^create/$', views.PropertyCreateView.as_view(), name='property_add'),
    url(r'^(?P<pk>\d+)/edit/$', views.PropertyUpdateView.as_view(), name='property_edit'),
    url(r'^(?P<pk>\d+)/delete/$', views.PropertyDeleteView.as_view(), name='delete'),
    url(r'^(?P<pk>\d+)/image/$', views.PropertyImageUpdateView.as_view(), name='property_image_update'),
    url(r'^save/$', views.add_bookmark,
        name='save'),
    url(r'^my_save/$', views.BookmarkListView.as_view(), name='my_save'),
    url(r'^about-us/', views.about, name='about'),
    url(r'^dashboard/', views.dashboard, name='dashboard'),
    url(r'^message_agent/(?P<premise_id>\d+)/$', views.message_agent, name='message_agent'),
    url(r'^message/', views.message_list, name='message_list'),
    url(
        r'^county-autocomplete/$',
        CountyAutocomplete.as_view(),
        name='county-autocomplete',
    ),
    url(r'^my_services/$', views.ManageServiceListView.as_view(), name='my_services'),
    url(r'^create_service/$', views.ServiceCreateView.as_view(), name='service_add'),
    url(r'^(?P<pk>\d+)/service_edit/$', views.SericeUpdateView.as_view(), name='service_edit'),
    url(r'^(?P<pk>\d+)/delete_service/$', views.ServiceDeleteView.as_view(), name='service_delete'),
    url(r'^category/(?P<categories>[-\w]+)/$',
        views.category_detail,
        name='category-detail')
]

platia/models.py
from __future__ import unicode_literals
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager

from django.db import models


class Category(models.Model):

    title = models.CharField(max_length=50)
    detail = models.TextField(blank=True)
    date_added = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-date_added',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title


class Trip(models.Model):
    AVAILABILITY = (
        ('yes', 'YES'),
        ('no', 'NO'))
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=250, unique_for_date='date_added', default='trips')
    date_added = models.DateTimeField(auto_now=True)
    price = models.DecimalField(max_digits=11, decimal_places=2)
    detail = models.TextField()
    start = models.DateField(blank=True)
    End = models.DateField(blank=True)
    summary = models.TextField()
    category = models.ForeignKey(Category)
    included = models.TextField()
    excluded = models.TextField()
    availability = models.CharField(max_length=50, choices=AVAILABILITY, default='no')
    photo = ProcessedImageField(upload_to='trips', processors=[ResizeToFill(1778, 1000)],
                                format='JPEG',
                                options={'quality': 100}, blank=True)
    tags = TaggableManager()


    class Meta:
        ordering = ('-date_added',)
        verbose_name_plural = 'Trips'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('tour:trip-detail', args=[self.date_added.year,
                                                   self.date_added.strftime('%m'),
                                                   self.date_added.strftime('%d'),
                                                   self.slug])


class Image(models.Model):
    title = models.CharField(max_length=100)
    date_added = models.DateTimeField(auto_now=True)
    image = ProcessedImageField(upload_to='images', processors=[ResizeToFill(1024, 767)],
                                format='JPEG',
                                options={'quality': 100})
    trip = models.ForeignKey(Trip, related_name='images')

    class Meta:
        ordering = ('-date_added',)

    def __str__(self):
        return self.title

platia/views.py
from django.shortcuts import render, get_object_or_404
from .models import Trip, Image
from taggit.models import Tag
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count


def travel(request):
    return render(request, 'tour/index.html')


def alltrips(request, tag_slug=None):
    trips = Trip.objects.all().order_by('-date_added')
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        trips = trips.filter(tags__in=[tag])

    paginator = Paginator(trips, 6)
    page = request.GET.get('page')
    try:
        trips = paginator.page(page)
    except PageNotAnInteger:
        trips = paginator.page(1)
    except EmptyPage:
        trips = paginator.page(paginator.num_pages)
    return render(request, 'tour/trips/alltrips.html', {'trips': trips, 'page': page, 'tag': tag})


def trip_detail(request, year, month, day, trip):
    trip = get_object_or_404(Trip, slug=trip)
    image = Image.objects.filter(trip=trip)
    trip_tag_ids = trip.tags.values_list('id', flat=True)
    similar_trips = Trip.objects.filter(tags__in=trip_tag_ids).exclude(id=trip.id)
    similar_trips = similar_trips.annotate(same_tags=Count('tags')).order_by('-same_tags', '-date_added')[:5]
    return render(request, 'tour/trips/trip_detail.html', {'trip': trip, 'image': image, 'similar_trips': similar_trips})

platia/templates/tour/main.html
{%load i18n staticfiles %}
<!doctype html>
<html class="no-js" lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Makao-Homes For Everyone</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.0/css/foundation-flex.css">
      <link href="{% static "css/foundation.css" %}" rel="stylesheet">

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <link href="{% static "css/app.css" %}" rel="stylesheet">
    <link href="{% static "fonts/slick.svg" %}" rel="stylesheet">
	<link href="{% static "fonts/slick.eot" %}" rel="stylesheet">
	<link href="{% static "fonts/slick.ttf" %}" rel="stylesheet">
	<link href="{% static "fonts/slick.woff" %}" rel="stylesheet">
	<link href="{% static "css/slick-theme.css" %}" rel="stylesheet">
	<link href="{% static "css/" %}" rel="stylesheet">

  <link href="https://fonts.googleapis.com/css?family=Chela+One|Coda+Caption:800|Fira+Sans|Gaegu|Hind|Knewave|Lato|Libre+Baskerville|Lora|Markazi+Text|Merienda|Merriweather|Montserrat|Noto+Sans|Noto+Serif|Open+Sans|Open+Sans+Condensed:300|Oswald|PT+Sans|PT+Sans+Narrow|Playfair+Display|Poppins|Raleway|Roboto|Roboto+Condensed|Roboto+Slab|Rubik|Slabo+27px|Source+Sans+Pro|Ubuntu" rel="stylesheet">
  </head>
  <body>
   <div data-sticky-container>
  <nav class="fixed top-bar topbar-responsive">
  <div class="top-bar-title">
    <span data-responsive-toggle="topbar-responsive" data-hide-for="medium">
      <button class="menu-icon" type="button" data-toggle></button>
    </span>
    <a class="topbar-responsive-logo" style="font-family:'Oswald', Bold; font-size: 30px; color: whitesmoke" href="{% url 'index' %}"><strong>Makao</strong></a>
  </div>
  <div id="topbar-responsive" class="topbar-responsive-links">
    <div class="top-bar-right">
     <ul class="menu simple vertical medium-horizontal">
     {% if request.user.is_authenticated  %}
         <li style="font-family:'Oswald', bold; font-size: 20px; color: white"> Welcome {{ user.username|capfirst }}</li>
      {% endif %}
      {% if request.user.is_authenticated and user.is_profile %}

          <li style="font-family:'Oswald', bold; font-size: 20px; color: white"> <a href="{% url 'finders:profile' %}"> My Profile</a></li>
          <li style="font-family:'Oswald', bold; font-size: 20px; color: white"> <a href="{% url 'premise:dashboard' %}"> My Dashboard</a></li>
      {% endif %}

        <li style="font-family:'Oswald', bold; font-size: 20px; color: black"><a href="{% url 'premise:about' %}">About Us</a></li>

      {% if  not request.user.is_authenticated %}
<li style="font-family:'Playfair Display', serif; font-size: 20px; color: black">
          <a href="{% url 'finders:user_registration' %}"><button type="button" class="button hollow topbar-responsive-button">
              Sign Up </button></a>
</li>
      {% endif %}
          {% if request.user.is_authenticated %}
<li style="font-family:'Playfair Display', serif; font-size: 20px; color: black">
          <a href="{% url 'logout' %}"><button type="button" class="button hollow topbar-responsive-button">
              Logout </button></a>
</li>

{% else %}
    <li>
         <a href="{% url 'user_login' %}"> <button type="button" class="button hollow topbar-responsive-button">
             Login</button></a>
</li>
          {% endif %}

      </ul>
    </div>
  </div>
</nav>
   {% for message in messages %}
    {% if 'success' in message.tags %}
<div data-closable class="callout alert-callout-border success">
  <strong><i class="fa fa-check"></i><i class="fa fa-check"></i></strong> - {{ message|safe }}.

  <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
    <span aria-hidden="true">&times;</span>
  </button>
</div>
    {% endif %}
{% endfor %}
{% for message in messages %}
    {% if 'error' in message.tags %}
<div data-closable class="callout alert-callout-border alert radius">
  <strong>OOPS</strong> - {{ message|safe }}.
  <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
    <span aria-hidden="true">&times;</span>
  </button>
</div>
    {% endif %}
{% endfor %}
</div>
  {% block content %}
  {% endblock %}

 <div id="engadget-footer-social-container">
    <footer id="engadget-footer-social">

    </footer>
</div>




    <script src="{% static 'js/vendor/jquery.js' %}"></script>
    <script src="{% static 'js/vendor/what-input.js' %}"></script>
    <script src="{% static 'js/vendor/foundation.js' %}"></script>
   <script src="{% static 'smart-selects/admin/js/chainedfk.js' %}"></script>
  <script src="{% static 'smart-selects/admin/js/bindfields.js' %}"></script>
    <script src="{% static 'js/app.js' %}"></script>
  <script src="{% static 'django_ajax/js/jquery.ajax.min.js' %}"></script>
   <script>

$('#saves').click(function () {
    var id;
    id = $(this).attr('data-id');
    $.ajax('/premise/save/', {premise_id : id}, function () {
        $('#saves').hide();
    });

});
   </script>
<script>
$('.responsive').slick({
  dots: true,
  infinite: true,
  speed: 300,
  slidesToShow: 4,
  slidesToScroll: 4,
  responsive: [
    {
      breakpoint: 1024,
      settings: {
        slidesToShow: 3,
        slidesToScroll: 3,
        infinite: true,
        dots: true
      }
    },
    {
      breakpoint: 600,
      settings: {
        slidesToShow: 2,
        slidesToScroll: 2
      }
    },
    {
      breakpoint: 480,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1
      }
    }
    // You can unslick at a given breakpoint now by adding:
    // settings: "unslick"
    // instead of a settings object
  ]
});
</script>

  <script type="text/javascript">
    $(document).ready(function(){
      $('.multiple-items').slick({
  infinite: true,
  arrows:true,
  slidesToShow: 4,
  slidesToScroll: 1,
  dots:false,
       responsive: [
    {
      breakpoint: 1024,
      settings: {
        slidesToShow: 3,
        slidesToScroll: 3,
        infinite: true,
        dots: true
      }
    },
    {
      breakpoint: 600,
      settings: {
        slidesToShow: 2,
        slidesToScroll: 2
      }
    },
    {
      breakpoint: 480,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1
      }
    }
    // You can unslick at a given breakpoint now by adding:
    // settings: "unslick"
    // instead of a settings object
  ]

});
    });
  </script>
    <script type="text/javascript">
    $(document).ready(function(){
      $('.deals').slick({
  infinite: true,
  arrows:true,
  slidesToShow: 4,
  slidesToScroll: 1,
  dots:false,
          responsive: [
    {
      breakpoint: 1024,
      settings: {
        slidesToShow: 3,
        slidesToScroll: 3,
        infinite: true,
        dots: true
      }
    },
    {
      breakpoint: 600,
      settings: {
        slidesToShow: 2,
        slidesToScroll: 2
      }
    },
    {
      breakpoint: 480,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1
      }
    }
    // You can unslick at a given breakpoint now by adding:
    // settings: "unslick"
    // instead of a settings object
  ]

});
    });
  </script>
  </body>
</html>